### ISSUE TITLE
Cannot open circ files correctly.

### ISSUE THREAD

**Issue by pmanolak** [Pharos1/Logisim-Custom-CPU#1]
It seems that circ files cannot be opened correctly with Logisim. either there are missing components in circuit design, or error raised for missing library (CPUForSnake: The built-in library BFH-Praktika is not available in this version.).

Could you please clarify for which version of Logisim these files were designed to be run?
I have tested on Logisim v2.7.2 and Logisim Evolution v3.8.0

![Screenshot from 2023-06-04 23-50-43](https://github.com/Pharos1/Logisim-Custom-CPU/assets/1267874/2f437e71-2f0d-4d16-95a4-70983f44fe86)

![Screenshot from 2023-06-04 23-48-26](https://github.com/Pharos1/Logisim-Custom-CPU/assets/1267874/50acc541-8657-492c-96ce-f253e453b2b7)

![Screenshot from 2023-06-04 23-49-24](https://github.com/Pharos1/Logisim-Custom-CPU/assets/1267874/d3e9969a-dce3-4669-a9c4-471ee87aaadc)

![Screenshot from 2023-06-04 23-49-37](https://github.com/Pharos1/Logisim-Custom-CPU/assets/1267874/8d0ba7f5-b093-47a8-8031-fa16fb91140b)

Thanks a lot in advance.

Regards,
Panagiotis.

**Comment by Pharos1** [comment]
Hi, thank you for posting your issue, I didn't think about that when posting my video and I don't have my pc near, but I opened the .circ with my phone and it says the version is 3.7.2 for logisim-evolution, at least the snake version. You can open any .circ with any text editor to see what version it is intended for. I am going to edit my repository.

**Comment by Pharos1** [comment]
Well, you didn't reply, but I am pretty sure this will solve your issue so I am closing it.
